### ISSUE TITLE
A documentation

### ISSUE THREAD

**Issue by xgrommx** [danylaporte/asyncplify#1]
Hello @danylaporte. When do you plan improve a documentation? If you wish I would like help you =) For example I made it for RxJs http://xgrommx.github.io/rx-book

**Comment by danylaporte** [comment]
Hi xgrommx. This is very nice. I don't have enough time right now to write a proper documentation. I would be very happy if you write some kind of documentation. Btw your book seems very well written.

There is some minor differences between Rxjs and Asyncplify such:
- everything is pausable / resumable. 
- flatMap supports a maxConcurrency which do almost.
- obsolete operators will not be implemented.

If you do a pullrequest, I will merge it.
Thanks for your help.

**Comment by xgrommx** [comment]
I glad if I can help you. But maybe I could be wrong but Rxjs can be pausable with this https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/rx.backpressure.md. Also what do you mean about obsolete operators?

**Comment by xgrommx** [comment]
Also I created some performance test:

``` js
var _ = require('lodash');
var Kefir = require('kefir');
import {Observable} from 'rx';
import sig from 'sig-js';
import Asyncplify from 'asyncplify';
import Immutable from 'immutable';
import Streamly from './streamlyjs.js';

var prettyMs = require('pretty-ms');
var items = _.range(100000);
var now = new Date();

sig(items)
    .map(x => x * x)
    .each(() => {}).done().teardown(sig.log, `Sig ${prettyMs(new Date() - now)}`).end();
now = new Date();

Asyncplify.fromArray(items).map(x => x * x).subscribe({
    emit: (x) => {},
    end: () => console.log('Asyncplify', prettyMs(new Date() - now))
});

now = new Date();

Observable.from(items).map(x => x * x).subscribe((x) => {

}, (e) => {}, () => console.log('Rx', prettyMs(new Date() - now)));

Streamly.fromArray = function fromArray(values) {
    var stream = new Streamly.EventStream();

    for(var i = 0; i < values.length; i++) {
        (function(k) {
            stream.onActivation(function(theStream) {
                theStream.emit(values[k]);
            });
        } (i));
    }

    return stream;
};

now = new Date();

var streamlyStream = Streamly.fromArray(items).map(x => x * x);

streamlyStream.onValue(x => {});
streamlyStream.onEnd(() => console.log('Streamly', prettyMs(new Date() - now)));

now = new Date();

var kefirStream = Kefir.later(0, items).flatten().map(x => x * x);

kefirStream.onValue(x => {});
kefirStream.onEnd(() => console.log('Kefir', prettyMs(new Date() - now)));

now = new Date();

var kefirStream2 = Kefir.sequentially(0, items).map(x => x * x);

kefirStream2.onValue(x => {});
kefirStream2.onEnd(() => console.log('Kefir2', prettyMs(new Date() - now)));

now = new Date();

var kefirStream3 = Kefir.sequentially(0, _.chunk(items, 100)).flatten().map(x => x * x);

kefirStream3.onValue(x => {});
kefirStream3.onEnd(() => console.log('Kefir3', prettyMs(new Date() - now)));
```

And this is result

```
Sig 166ms
Asyncplify 3ms
Rx 154ms
Streamly 75ms
Kefir 125ms
Kefir3 1.1s
Kefir2 1m 40.7s
```

Nice result =) But what do you think about support transducers? In RxJs I proposed it https://github.com/Reactive-Extensions/RxJS/issues/326

**Comment by danylaporte** [comment]
For obsolete, I mean deprecated operators. In the Rxjs documentation on github, there are many operators marked as deprecated. I don't plan to implement them.

For backpressure, they are saying in the documentation that cold observable don't support pause / resume. See the note on [Pausable Observables](https://github.com/Reactive-Extensions/RxJS/blob/f3f53dd1f2682ea5437ec62916c2e9f299af2b89/doc/gettingstarted/backpressure.md#pausable-observables).

For transducers, it could be a really nice thing. I will do it. Btw, I have already implemented a pipe operator that is close to what transduce is producing.

Here is an example of the pipe usage:

``` js
var asyncplify = require('asyncplify');

function filterGreaterThan(value) {
    return function (source) {
        return source.filter(x => x > value)
    }
}

asyncplify
    .fromArray([1, 2, 3])
    .pipe(filterGreaterThan(2))
    .subscribe(function (v) {
        console.log(v);
    });

// emit 3
// end.
```

Thanks for the benchmark result. Always nice to see good results.

**Comment by xgrommx** [comment]
Nice explain =) Thank you. I included your library at that page http://xgrommx.github.io/rx-book/content/similar_libraries/index.html

**Comment by xgrommx** [comment]
@danylaporte I was started working on book http://xgrommx.github.io/asyncplify-book/content/instance_methods/count.html. When I will have a lot time, I continue working on this book. If you can help me I will glad =)

**Comment by xgrommx** [comment]
Also about catching errors. In rx exists onError in subscribe method. What is it in asyncplify.

**Comment by xgrommx** [comment]
About `groupBy` where can I get keys? In flatMap emitted only values.

**Comment by danylaporte** [comment]
Catching errors, in asyncplify is really the same as in Rxjs except that there is no specific callback. The end function will receive the error if there is one as the first parameter, otherwise, it's null. Now, there is no catch operator for now, it's a work in progress.

You're right about the groupBy operator. I forgot about the key. I have published a new version of the package with the fix. 

For flatMap, i don't understand the issue.

Thanks for the review and for your time.

**Comment by xgrommx** [comment]
@danylaporte I talk about that:

``` js
var items = ["Apple", "Ananas", "Mango", "Banana", "Beer"];

Asyncplify.fromArray(items)
    .groupBy(function(s) { return s[0]; })
    .flatMap(function (group) {
        return group
          .toArray()
          .map(function (items) { 
            return { key: group.key, value: items };
        });
    })
    .subscribe(function (s) { console.log(s); });
```

Now it's work correct. Thanks.

**Comment by xgrommx** [comment]
Also about `zip` operator. I think will be better if  `zip` operator will have mapper, like so:

``` js
asyncplify.zip([asyncplify.fromArray([1,2,3,4]), asyncplify.asyncplify.fromArray([5,6,7])], (a, b) => {
  return {a: a, b: b};
});

//result => {a: 1, b: 5}, {a: 2, b: 6}, {a: 3, b: 7}
```

**Comment by xgrommx** [comment]
This example doesn't work:

``` js
Asyncplify.interval(1000, 1).map(function() {
            return 10;
        }).sum().subscribe(console.log.bind(console));
```

I guess problem with `sum`

I tried it:

``` js
    function Sum(mapper, on, source) {
        this.hasValue = false;
        this.mapper = mapper;
        this.value = 0;
        this.on = on;
        this.source = null;
        on.source = this;
        source._subscribe(this);
    }
    Sum.prototype = {
        emit: function (value) {
            this.value += this.mapper(value) || 0;
            this.hasValue = true;
            this.on.emit(this.value);
        },
        end: endThru,
        setState: setStateThru
    };
```

It's working now but I'm not sure that is right. Looks like it's work like `scan` :smile:

**Comment by xgrommx** [comment]
`merge` operator doesn't have `subscribe` with `pause` and `resume`. For example it's work:

``` js
var count = 0;
var sub = Asyncplify.interval(1000, 1).map(function(x) {
            return count++;
        }).subscribe(console.log.bind(console));
setTimeout(sub.pause.bind(sub), 2000);
setTimeout(sub.resume.bind(sub), 5000);
```

But that code dosen't work:

``` js
var count = 0;
var sub = Asyncplify.merge([Asyncplify.interval(1000, 1), Asyncplify.value(0)]).map(function(x) {
      return count++;
 }).subscribe(console.log.bind(console));
setTimeout(sub.pause.bind(sub), 2000);
setTimeout(sub.resume.bind(sub), 5000);
```

I got error like this `Uncaught TypeError: this.subscriptions[i].setState is not a function`

**Comment by danylaporte** [comment]
For the zip operator, i will add a mapper.

For the interval, i think you want the Range operator. You can use it like that:

``` js
asyncplify.range({ from: 1, end: 4, step: 2}).subscribe(console.log.bind(console));
//emit 1
//emit 3
//end.

// here is a shortcut:
asyncplify.range(2).subscribe(console.log.bind(console));
//emit 0
//emit 1
//end.
```

Interval operator is used to emit value after each period. see [Rxjs interval](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/interval.md)

Sum operator should work with Interval as well as with range but you need to take care of the ending because the stream will emit forever.

``` js
// emit a value at each 10 ms
asyncplify.interval(10).take(5).sum().subscribe(console.log.bind(console);
```

Thanks

**Comment by danylaporte** [comment]
I have added a mapper to the zip operator.

``` js
asyncplify
    .zip({
        items: [asyncplify.value(0), asyncplify.value(1)],
        mapper: function (x, y) { return { x: x, y: y}; }
    })
    .subscribe(console.log.bind(console))
// emit {x: 0, y: 1}
// end.
```

Hope it helps. :)

**Comment by danylaporte** [comment]
For the merge operator that does not support a pause / resume, i will check it. Thanks for reporting the issue.

**Comment by xgrommx** [comment]
Wow! Thank you @danylaporte. I have yet another problem with `merge` operator. I was starting create some wrapper for Angular.js with Asyncplify. But my `merge` with array of events doesn't emit some data. This is my [bin](http://jsbin.com/cogati/1/edit?html,js,output). I think this case is suitable for the scan operator. But this operator doesn't exists yet.

**Comment by danylaporte** [comment]
Nice. In this specific case, sum cannot be used because it does not return any intermediate result. I already plan to implement it, by adding an argument to specify that we want the intermediate results. This could be also supported by avg, count, etc to emit a result each time the value is changing. At this moment, the sum/count operator emit only a value when the stream complete. I will add this feature soon.

**Comment by xgrommx** [comment]
Thank you @danylaporte. I think `scan` or another aggregation operator is necessary in frp =)

**Comment by danylaporte** [comment]
You're right that scan is doing that. Just as a discussion, is it better to have a new parameter like this:

``` js
asyncplify.range(10).sum({ intermediate: true }).
```

so we could replicate the same behavior on all these operators:
count, avg, median, stdDeviation, ...

or is it better to have a different operator?  In later, what could be the name of all other operators (Count, avg, median, stdDeviation)?

**Comment by xgrommx** [comment]
How I understood now `sum` operator have behavior like a `scan` with `(x, y) => x + y` mapper? If yes, I think will be better have `scan` separately from `sum`. Also if we have `scan` we can implement `reduce` like so:

``` js
reduce= scan(fn, seed).last();
sum = reduce((x, y) => x + y, 0);
whatever = reduce(fn, seed);
```

I can mistake but I think it is good approach. So we need only `scan` =) Other operators will be implemented very easy.

**Comment by danylaporte** [comment]
ok, I will add a scan operator. Thank you.

**Comment by xgrommx** [comment]
@danylaporte Thanks. Now my example with angular work fine =)

**Comment by danylaporte** [comment]
Thanks, Merge is now fixed for the close / pause / resume.

**Comment by xgrommx** [comment]
@danylaporte Thanks =) When you plan add support for transducers?

**Comment by danylaporte** [comment]
I've just add a new transduce operator. I'm not sure if I have correctly implemented it. I will try to find more information on this subject to make sure it is correct.

**Comment by danylaporte** [comment]
@xgrommx How is the new transduce operator?

**Comment by xgrommx** [comment]
@danylaporte Sorry I don't have much time that try it. I'll do it later. Thanks. But if your test work correct I think it's right implementation.
